variable "aws_region" {
    description = "AWS region for all resources (Athena/Glue are regional)."
    type        = string
    default     = "us-east-1"
}

variable "suffix" {
    description = "Suffix appended to globally-unique resources (e.g. the S3 lake bucket). If left empty, a random 8-char hex suffix is generated."
    type        = string
    default     = ""
}

variable "fivetran_aws_account_id" {
    description = "Fivetran's AWS account ID, used as the trust principal for the Fivetran assume role."
    type        = string
    default     = "834469178297"
}

variable "fivetran_external_id" {
    description = "External ID generated by Fivetran when configuring the destination. Paste the value Fivetran provides on the destination setup screen."
    type        = string
    sensitive   = true
}

variable "dbt_iam_user_arn" {
    description = "ARN of the IAM user (created manually) that the dbt runner uses to assume the lighthouse-odi-dbt role. Example: arn:aws:iam::123456789012:user/dbt-runner"
    type        = string
}

variable "tags" {
    description = "Default tags applied to every resource."
    type        = map(string)
    default = {
        Project     = "Media-ODI-Demo"
        Owner       = "Lighthouse Media Demo"
        Environment = "dev"
    }
}
